/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Supplier;
import model.SupplierDirectory;
import ui.admin.AdminWorkAreaJPanel;
import ui.supplier.SupplierWorkAreaJPanel;

/**
 *
 * @author rutuja
 */
public class LoginScreen extends javax.swing.JPanel {

    /**
     * Creates new form LoginScreen
     */
    JPanel mainWorkArea;
    SupplierDirectory supplierDirectory;
    Supplier SelectedSupplier = null;
    
    public LoginScreen(JPanel mainWorkArea, SupplierDirectory supplierDirectory) {
        initComponents();
        this.setSize(2000,2000);
        this.mainWorkArea = mainWorkArea;
        this.supplierDirectory = supplierDirectory;
        
        populateRoleCombo();
        populateSupplierCombo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogin = new javax.swing.JButton();
        cmbSuppliers = new javax.swing.JComboBox<>();
        lblSupplier = new javax.swing.JLabel();
        cmbRoles = new javax.swing.JComboBox<>();
        lblRole = new javax.swing.JLabel();

        setBackground(new java.awt.Color(208, 228, 249));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        cmbSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSuppliersActionPerformed(evt);
            }
        });
        add(cmbSuppliers, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 134, -1));

        lblSupplier.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        lblSupplier.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSupplier.setText("Select Supplier:");
        add(lblSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        cmbRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRolesActionPerformed(evt);
            }
        });
        add(cmbRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 134, -1));

        lblRole.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        lblRole.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRole.setText("Choose Role:");
        add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
       
       JPanel selectedPanel = (JPanel) cmbRoles.getSelectedItem();
       if (selectedPanel.getClass() == SupplierWorkAreaJPanel.class){
           if (SelectedSupplier == null){
               JOptionPane.showMessageDialog(this,"Please select a supplier to login under supplier Role.");
               return;
               
           }else{
               selectedPanel = new SupplierWorkAreaJPanel(mainWorkArea,SelectedSupplier);
           }
       }
       mainWorkArea.add("WorkAreaPanel",selectedPanel);
       CardLayout layout = (CardLayout) mainWorkArea.getLayout();
       layout.next(mainWorkArea);
 
    }//GEN-LAST:event_btnLoginActionPerformed

    private void cmbSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSuppliersActionPerformed
        // TODO add your handling code here:
       if (cmbSuppliers.getSelectedItem() == null)
           return;
       SelectedSupplier = (Supplier) cmbSuppliers.getSelectedItem();
    }//GEN-LAST:event_cmbSuppliersActionPerformed

    private void cmbRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRolesActionPerformed
        // TODO add your handling code here:
        updateSupplierVisibility();
    }//GEN-LAST:event_cmbRolesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<Object> cmbRoles;
    private javax.swing.JComboBox<Supplier> cmbSuppliers;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblSupplier;
    // End of variables declaration//GEN-END:variables

    private void updateSupplierVisibility() {
        if((cmbRoles.getSelectedItem()== null) || (cmbRoles.getSelectedItem().getClass() == AdminWorkAreaJPanel.class)){
            lblSupplier.setVisible(false);
            cmbSuppliers.setVisible(false);
            return;
        }
        else if(cmbRoles.getSelectedItem().getClass() == SupplierWorkAreaJPanel.class){
            lblSupplier.setVisible(true);
            cmbSuppliers.setVisible(true);            
        }
    }

    private void populateRoleCombo() {
        cmbRoles.removeAllItems();
        
        AdminWorkAreaJPanel adminPanel = new AdminWorkAreaJPanel(mainWorkArea, supplierDirectory);
        SupplierWorkAreaJPanel supplierPanel = new SupplierWorkAreaJPanel(mainWorkArea,SelectedSupplier) ;
        
        cmbRoles.addItem(adminPanel);
        cmbRoles.addItem(supplierPanel);
        
    }

    public void populateSupplierCombo() {
        cmbSuppliers.removeAllItems();
        
        for(Supplier supplier : supplierDirectory.getSupplierList()){
            cmbSuppliers.addItem(supplier);
            //System.out.println("Printling suppliers: "+supplier);
        }
    }
}
