/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SupplierRole;

import Business.Supplier;
import Business.SupplierDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author rutuja
 */
public class LoginSupplier extends javax.swing.JPanel {

    /**
     * Creates new form LoginSupplier
     */
    private JPanel userProcessContainer;
    private SupplierDirectory supplierDirectory;
    
    public LoginSupplier(JPanel userProcessContainer, SupplierDirectory supplierDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.supplierDirectory = supplierDirectory;
        this.setSize(2000,2000);
        
        supplierComboBox.removeAllItems();;
        for (Supplier supplier : supplierDirectory.getSupplierList()) {
        supplierComboBox.addItem(supplier);

          
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbllogin = new javax.swing.JLabel();
        lblSupplierName = new javax.swing.JLabel();
        btnGo = new javax.swing.JButton();
        txtname = new javax.swing.JTextField();
        supplierComboBox = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(144, 177, 177));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbllogin.setBackground(new java.awt.Color(144, 177, 177));
        lbllogin.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lbllogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllogin.setText("Supplier Login");
        add(lbllogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 25, 426, -1));

        lblSupplierName.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        lblSupplierName.setText("Supplier Name:");
        add(lblSupplierName, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 105, -1, -1));

        btnGo.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        btnGo.setText("GO>>");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });
        add(btnGo, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 102, -1, -1));
        add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 144, 96, -1));

        supplierComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        supplierComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierComboBoxActionPerformed(evt);
            }
        });
        add(supplierComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 102, 115, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        // TODO add your handling code here:
        Supplier supplier = (Supplier) supplierComboBox.getSelectedItem();
        SupplierWorkAreaJPanel swajp = new SupplierWorkAreaJPanel(userProcessContainer, supplier);
        userProcessContainer.add("SupplierWorkAreaJPanel", swajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnGoActionPerformed

    private void supplierComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierComboBoxActionPerformed
//
    }//GEN-LAST:event_supplierComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGo;
    private javax.swing.JLabel lblSupplierName;
    private javax.swing.JLabel lbllogin;
    private javax.swing.JComboBox supplierComboBox;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
