/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;

import Business.MasterOrderCatalog;
import Business.Order;
import Business.OrderItem;
import Business.Product;
import Business.Supplier;
import Business.SupplierDirectory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author rutuja
 */
public class BrowseProducts extends javax.swing.JPanel {

    /**
     * Creates new form BrowseProducts
     */
    private JPanel userProcessContainer;
    private SupplierDirectory supplierDirectory;
    private MasterOrderCatalog masterOrderCatalog;
    private Order order;
    boolean isCheckedOut = false;
    public BrowseProducts(JPanel userProcessContainer,SupplierDirectory supplierDirectory ,MasterOrderCatalog masterOrderCatalog) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.supplierDirectory = supplierDirectory;
        this.masterOrderCatalog = masterOrderCatalog;
        this.setSize(2000,2000);
        
    }
    private void populateSuppCombo(){
        suppComboBox1.removeAll();
        
        for(Supplier supplier : supplierDirectory.getSupplierList()){
           suppComboBox1.addItem(supplier);
        }
        
        popuplateProductTable();
        if(!isCheckedOut){
            order = new Order();
        }
    }

    private void popuplateProductTable(){
        
        DefaultTableModel dtm = (DefaultTableModel) productTable.getModel();
        Supplier supplier = (Supplier)suppComboBox1.getSelectedItem();
        dtm.setRowCount(0);
        if(supplier != null){
            
            for (Product product : supplier.getProductCatalog().getProductCatalog()){
                
                Object row[] = new Object[4];
                row [0] = product;
                row[1] = product.getModelNumber();
                row[2] =  product.getPrice();
                row[3]=product.getAvail();
                dtm.addRow(row);
                
            }
        }       
    }

    private  void searchProductTable(String prodName){
        
        int rowCount = productTable.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel) productTable.getModel();
        
        for ( int i = rowCount -1; i>0; i--){
            dtm.removeRow(i);
        }
        for(Supplier s: supplierDirectory.getSupplierList()){
            for(Product p:s.getProductCatalog().getProductCatalog()){
                if(prodName.equalsIgnoreCase(p.getProdName())){
                    
                    Object row[] = new Object[4];
                row [0] = p;
                row[1] = p.getModelNumber();
                row[2] =  p.getPrice();
                row[3]=p.getAvail();
                dtm.addRow(row);
                }
            }
        }
    }
    
    void refreshorderTable(){
        
        int rowCount = orderTable.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel) productTable.getModel();
         for ( int i = rowCount -1; i>0; i--){
            dtm.removeRow(i);
        }
         for(OrderItem o : order.getOrderItemList()){
             
            Object[] row = new Object[4];
            row[0] = o;
            row[1] = o.getSaleprice();
            row[2] = o.getQauntiry();
            row[3] =o.getQauntiry() *o.getSaleprice();
            dtm.addRow(row);
            
         }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewProdjButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        addtoCartButton6 = new javax.swing.JButton();
        quantitySpinner = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        btnSearchProduct = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        suppComboBox1 = new javax.swing.JComboBox();
        txtSalesPrice = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnViewOrderItem = new javax.swing.JButton();
        btnModifyQuantity = new javax.swing.JButton();
        btnRemoveOrderItem = new javax.swing.JButton();
        btnCheckOut = new javax.swing.JButton();
        txtSearchKeyWord = new javax.swing.JTextField();
        txtNewQuantity = new javax.swing.JTextField();

        setBackground(new java.awt.Color(144, 177, 177));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewProdjButton2.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        viewProdjButton2.setText("View Product Detail");
        viewProdjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProdjButton2ActionPerformed(evt);
            }
        });
        add(viewProdjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 310, 179, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/CustomerRole/bestbuy.gif"))); // NOI18N
        jLabel4.setText("Have a wonderful shopping experience !");
        jLabel4.setIconTextGap(7);
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 16, 588, -1));

        addtoCartButton6.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        addtoCartButton6.setText("Add To Cart");
        addtoCartButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtoCartButton6ActionPerformed(evt);
            }
        });
        add(addtoCartButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 310, 179, -1));

        quantitySpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        add(quantitySpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 311, 69, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel5.setText("Quantity:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 312, -1, -1));

        productTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Product Id", "Price", "Avail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(productTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 175, 708, 110));

        btnSearchProduct.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        btnSearchProduct.setText("Search Product");
        btnSearchProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchProductActionPerformed(evt);
            }
        });
        add(btnSearchProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 82, 152, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel6.setText("Sales Price:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 312, -1, -1));

        suppComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppComboBox1ActionPerformed(evt);
            }
        });
        add(suppComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 84, 206, -1));
        add(txtSalesPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 69, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Supplier");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 79, 80, 30));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel7.setText("Item in Cart:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 367, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Product Catalog");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 143, 240, -1));

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Item Name", "Price", "Quantity", "Total Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(orderTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 405, 708, 110));

        btnBack.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 28, -1, -1));

        btnViewOrderItem.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        btnViewOrderItem.setText("View Item");
        btnViewOrderItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewOrderItemActionPerformed(evt);
            }
        });
        add(btnViewOrderItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 533, 168, -1));

        btnModifyQuantity.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        btnModifyQuantity.setText("Modify Quantity");
        btnModifyQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyQuantityActionPerformed(evt);
            }
        });
        add(btnModifyQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 533, -1, -1));

        btnRemoveOrderItem.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        btnRemoveOrderItem.setText("Remove");
        btnRemoveOrderItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveOrderItemActionPerformed(evt);
            }
        });
        add(btnRemoveOrderItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 533, 168, -1));

        btnCheckOut.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnCheckOut.setText("Check out");
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });
        add(btnCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 580, 217, -1));
        add(txtSearchKeyWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 83, 206, -1));
        add(txtNewQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 534, 98, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void viewProdjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProdjButton2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_viewProdjButton2ActionPerformed

    private void addtoCartButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtoCartButton6ActionPerformed
        // TODO add your handling code here:
        int selectedRow = productTable.getSelectedRow();
        Product selectedProduct;
        int salesPrice = 0;
        //no row selected
        if(selectedRow <0){

            JOptionPane.showMessageDialog(this, "Please select a product","warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        else{
            selectedProduct = (Product)productTable.getValueAt(selectedRow,0);

        }
        //sale price validation
        try{
            salesPrice = Integer.parseInt(txtSalesPrice.getText());

        } catch(Exception e){

            JOptionPane.showMessageDialog(this,"entered Price should be more thatn actual", "Warning",JOptionPane.WARNING_MESSAGE);
        }
        //sale price getter than actual
        if(salesPrice < selectedProduct.getPrice()){
            JOptionPane.showMessageDialog(this, "entered price should be more than actual","Warning",JOptionPane.WARNING_MESSAGE);
        }
        //qty more than 0
        int fetchedqty = (Integer)quantitySpinner.getValue();
        if(fetchedqty <=0){
            JOptionPane.showMessageDialog(this, "qnty should be greater than zero","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        } else if ( fetchedqty <= selectedProduct.getAvail()){
            boolean alreadyPresent = false;
            for(OrderItem orderItem : order.getOrderItemList()){
                if(orderItem.getProduct()== selectedProduct){
                    int oldAvail = selectedProduct.getAvail();
                    int newAvail = oldAvail-fetchedqty;
                    selectedProduct.setAvail(newAvail);
                    orderItem.setQauntiry(fetchedqty+ orderItem.getQauntiry());
                    alreadyPresent = true;
                    refreshorderTable();
                    popuplateProductTable();
                    break;
                }

            }

            if(!alreadyPresent){

                int oldAvail = selectedProduct.getAvail();
                int newAvail = oldAvail - fetchedqty;
                selectedProduct.setAvail(newAvail);
                order.addOrderItem(selectedProduct,fetchedqty, salesPrice);
                refreshorderTable();
                popuplateProductTable();
            }
        }
            

    }//GEN-LAST:event_addtoCartButton6ActionPerformed

    private void btnSearchProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchProductActionPerformed

        String prodName = txtSearchKeyWord.getText();
        searchProductTable(prodName);
    }//GEN-LAST:event_btnSearchProductActionPerformed

    private void suppComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppComboBox1ActionPerformed
        // TODO add your handling code here:
        popuplateProductTable();

    }//GEN-LAST:event_suppComboBox1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewOrderItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOrderItemActionPerformed

    }//GEN-LAST:event_btnViewOrderItemActionPerformed

    private void btnModifyQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyQuantityActionPerformed
        // TODO add your handling code here:
        int selectedRow = orderTable.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Select a row","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!txtNewQuantity.getText().isEmpty() && !txtNewQuantity.getText().equals("0")){
            OrderItem orderItem = (OrderItem) orderTable.getValueAt(selectedRow,0);
            int  currentAvail = orderItem.getProduct().getAvail();
            int oldqty = orderItem.getQauntiry();
            int newqty = Integer.parseInt(txtNewQuantity.getText());

            if(newqty > (currentAvail + oldqty)){
                JOptionPane.showMessageDialog(this, "qty more than availablity");

            }else{
                if (newqty <=0){
                    JOptionPane.showMessageDialog(this, "Invalid qty","warning",JOptionPane.WARNING_MESSAGE);
                    return;
                }
                orderItem.setQauntiry(newqty);
                orderItem.getProduct().setAvail(currentAvail + (oldqty - newqty));
                refreshorderTable();
                popuplateProductTable();
            }
        }else{
            JOptionPane.showMessageDialog(this, "qty can not be zero","waring",JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnModifyQuantityActionPerformed

    private void btnRemoveOrderItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveOrderItemActionPerformed

        int selectedRow = orderTable.getSelectedRow();
        if(selectedRow <=0){
            JOptionPane.showMessageDialog(this, "selecte a row","warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        OrderItem o = (OrderItem)orderTable.getValueAt(selectedRow, 0);
        int oldqty = o.getProduct().getAvail();
        int orderqty = o.getQauntiry();
        int newqty = oldqty + orderqty;
        o.getProduct().setAvail(newqty);

        order.removeOrderItem(o);
        JOptionPane.showMessageDialog(this,"The order item of"+orderqty+"of"+o+"has been remove");
        refreshorderTable();
        popuplateProductTable();

    }//GEN-LAST:event_btnRemoveOrderItemActionPerformed

    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
        // TODO add your handling code here:
        if(order.getOrderItemList().size()>0){
            masterOrderCatalog.addorder(order);
            isCheckedOut = true;
            JOptionPane.showMessageDialog(this,"order addedd successfully" );
            order = new Order();
            refreshorderTable();
            popuplateProductTable();

        }else{
            JOptionPane.showMessageDialog(this, "No order exists","Warning",JOptionPane.WARNING_MESSAGE);

        }

    }//GEN-LAST:event_btnCheckOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addtoCartButton6;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JButton btnModifyQuantity;
    private javax.swing.JButton btnRemoveOrderItem;
    private javax.swing.JButton btnSearchProduct;
    private javax.swing.JButton btnViewOrderItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable orderTable;
    private javax.swing.JTable productTable;
    private javax.swing.JSpinner quantitySpinner;
    private javax.swing.JComboBox suppComboBox1;
    private javax.swing.JTextField txtNewQuantity;
    private javax.swing.JTextField txtSalesPrice;
    private javax.swing.JTextField txtSearchKeyWord;
    private javax.swing.JButton viewProdjButton2;
    // End of variables declaration//GEN-END:variables
}
