/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Patient;
import Model.Person;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rutuja
 */
public class CreatePatientPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePatient
     */
    private JPanel userProcessContainer;    
    private ArrayList<Patient> patientList;
    private Person person;
    private Patient patient;
    private int AgeGroup;
    
    public CreatePatientPanel(Person person, JPanel userProcessContainer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.patientList = patientList;
        this.person = person;
                this.setSize(3000,3000);

        
        pNameTextField.setText(person.getFirstName());
        
        patient = new Patient();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        ageTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        docNameTextField = new javax.swing.JTextField();
        pharmacyTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pNameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pIDTextField = new javax.swing.JTextField();

        jLabel4.setBackground(new java.awt.Color(255, 255, 204));
        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setText("Age:");

        jLabel5.setBackground(new java.awt.Color(255, 255, 204));
        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setText("Primary Doctor Name:");

        jLabel6.setBackground(new java.awt.Color(255, 255, 204));
        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setText("Preffered Pharmacy:");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CREATE PATIENT INFORMATION");

        addBtn.setBackground(new java.awt.Color(255, 255, 204));
        addBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 204));
        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Patient Name:");

        pNameTextField.setEditable(false);
        pNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pNameTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 204));
        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("Patient ID:");

        pIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pIDTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBtn)
                    .addComponent(pIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(docNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pharmacyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(357, 357, 357))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ageTextField, docNameTextField, pIDTextField, pNameTextField, pharmacyTextField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(docNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pharmacyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(addBtn)
                .addContainerGap(93, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:

       
        if(pIDTextField.getText().trim().isEmpty())   {
            JOptionPane.showMessageDialog(this, "Patient ID cannot be blank!", "Error", JOptionPane.OK_OPTION);
            pIDTextField.setBackground(Color.yellow);
        }
        else if(!pIDTextField.getText().matches("[0-9]*"))   {
            JOptionPane.showMessageDialog(this, "Patient ID cannot have special characters!", "Error", JOptionPane.OK_OPTION);
            pIDTextField.setBackground(Color.yellow);
        }
        else if(ageTextField.getText().trim().isEmpty())   {
            JOptionPane.showMessageDialog(this, "Age cannot be blank!", "Error", JOptionPane.OK_OPTION);
            ageTextField.setBackground(Color.yellow);
        }
        else if(!ageTextField.getText().matches("\\d+"))   {
            JOptionPane.showMessageDialog(this, "Age can only have digits!", "Error", JOptionPane.OK_OPTION);
            ageTextField.setBackground(Color.yellow);
        }
        else if(ageTextField.getText().matches("0"))   {
            JOptionPane.showMessageDialog(this, "Age cannot be zero!", "Error", JOptionPane.OK_OPTION);
            ageTextField.setBackground(Color.yellow);
        }
        else if(docNameTextField.getText().trim().isEmpty())   {
            JOptionPane.showMessageDialog(this, "Preffered Doctor Name cannot be blank!", "Error", JOptionPane.OK_OPTION);
            docNameTextField.setBackground(Color.yellow);
        }
        else if (!docNameTextField.getText().matches("[a-zA-Z ]*")){
            JOptionPane.showMessageDialog(this, "Please enter valid Primary Doctor Name!", "Error", JOptionPane.OK_OPTION);
            docNameTextField.setBackground(Color.yellow);
        }
        else if(pharmacyTextField.getText().trim().isEmpty())   {
            JOptionPane.showMessageDialog(this, "Pharmacy Name cannot be blank!", "Error", JOptionPane.OK_OPTION);
            pharmacyTextField.setBackground(Color.yellow);
        }
        else if (!pharmacyTextField.getText().matches("[a-zA-Z ]*")){
            JOptionPane.showMessageDialog(this, "Please enter valid Pharmacy Name!", "Error", JOptionPane.OK_OPTION);
            pharmacyTextField.setBackground(Color.yellow);
        }
        else    {

            patient.setpName(pNameTextField.getText());
            patient.setpID(Integer.parseInt(pIDTextField.getText()));
            patient.setAgeGroup(Integer.parseInt(ageTextField.getText()));
            patient.setDocName(docNameTextField.getText());
            patient.setPharmacy(pharmacyTextField.getText());

            person.getPatientList().add(patient);

            JOptionPane.showMessageDialog(this, "Patient Information is successfully saved!", "Information", JOptionPane.INFORMATION_MESSAGE);
            resetFields();

            AddVitalSign addVitalSign =  new AddVitalSign(patient, userProcessContainer);
            userProcessContainer.add("addVitalSign", addVitalSign);
            CardLayout layout = (CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void pNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pNameTextFieldActionPerformed

    private void pIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pIDTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JTextField docNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField pIDTextField;
    private javax.swing.JTextField pNameTextField;
    private javax.swing.JTextField pharmacyTextField;
    // End of variables declaration//GEN-END:variables

    private void resetFields() {
        pIDTextField.setText("");
        pIDTextField.setBackground(Color.white);
        pNameTextField.setText("");
        pNameTextField.setBackground(Color.white);
        ageTextField.setText("");
        ageTextField.setBackground(Color.white);
        docNameTextField.setText("");
        docNameTextField.setBackground(Color.white);
        pharmacyTextField.setText("");
        pharmacyTextField.setBackground(Color.white);
    }
}
