/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Person;
import Model.PersonDirectory;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rutuja
 */
public class CreatePersonPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateVital
     */
    private String ePattern = "^[a-zA-Z0-9.'*+/=?^_`{|}~-]+@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$";
    
    private JPanel userProcessContainer;
    private Person person;
    private PersonDirectory personDirectory;
    private ArrayList<Person> personList;
    
    public CreatePersonPanel(PersonDirectory personDirectory, JPanel userProcessContainer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.personDirectory = personDirectory;
        this.personList = personDirectory.getPersonList();
        this.setSize(3000,3000);

        
        person = new Person();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        middleNameTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dobTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        houseNumberTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cityTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        zipCodeTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        occupationTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        phoneNumberTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        createBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        communityTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(241, 199, 199));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(middleNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 118, 149, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 204));
        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel6.setText("Middle Name:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 123, -1, -1));
        add(dobTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 340, 149, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 204));
        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel12.setText("Date of Birth (YYYY/MM/DD):");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 345, -1, -1));

        houseNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                houseNumberTextFieldActionPerformed(evt);
            }
        });
        add(houseNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 194, 149, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 204));
        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel7.setText("House Number:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 194, -1, -1));
        add(cityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 232, 149, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 204));
        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel8.setText("City:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 237, -1, -1));
        add(zipCodeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 302, 149, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 204));
        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel9.setText("Zip Code:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 307, -1, -1));
        add(occupationTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 378, 149, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 204));
        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel10.setText("Occupation:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 383, -1, -1));
        add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 416, 149, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 204));
        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel11.setText("Email ID:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 421, -1, -1));
        add(phoneNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 456, 149, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 204));
        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel14.setText("Phone Number:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 461, -1, -1));

        createBtn.setBackground(new java.awt.Color(255, 255, 204));
        createBtn.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        createBtn.setText("Create");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 509, -1, -1));

        jLabel1.setBackground(new java.awt.Color(241, 199, 199));
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Person Profile");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 750, -1));
        add(firstNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 80, 149, -1));

        backBtn.setBackground(new java.awt.Color(255, 255, 204));
        backBtn.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 509, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 204));
        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel4.setText("First Name:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 85, -1, -1));
        add(lastNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 156, 149, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 204));
        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel5.setText("Last Name:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 161, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel2.setText("Community:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 275, -1, -1));
        add(communityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 270, 149, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:

        if(firstNameTextField.getText().trim().isEmpty())   {
            JOptionPane.showMessageDialog(this, "First Name cannot be blank!", "Error", JOptionPane.OK_OPTION);
            firstNameTextField.setBackground(Color.yellow);
        }
        else if (!firstNameTextField.getText().matches("[a-zA-Z]*")){
            JOptionPane.showMessageDialog(this, "Please enter valid First Name!", "Error", JOptionPane.OK_OPTION);
            firstNameTextField.setBackground(Color.yellow);
        }
        else if(lastNameTextField.getText().trim().isEmpty())   {
            JOptionPane.showMessageDialog(this, "Last Name cannot be blank!", "Error", JOptionPane.OK_OPTION);
            lastNameTextField.setBackground(Color.yellow);
        }
        else if (!lastNameTextField.getText().matches("[a-zA-Z]*")){
            JOptionPane.showMessageDialog(this, "Please enter valid Last Name!", "Error", JOptionPane.OK_OPTION);
            lastNameTextField.setBackground(Color.yellow);
        }
        else if(middleNameTextField.getText().trim().isEmpty())   {
            JOptionPane.showMessageDialog(this, "Middle Name cannot be blank!", "Error", JOptionPane.OK_OPTION);
            middleNameTextField.setBackground(Color.yellow);
        }
        else if (!middleNameTextField.getText().matches("[a-zA-Z]*")){
            JOptionPane.showMessageDialog(this, "Please enter valid Middle Name!", "Error", JOptionPane.OK_OPTION);
            middleNameTextField.setBackground(Color.yellow);
        }
        else if(houseNumberTextField.getText().trim().isEmpty())   {
            JOptionPane.showMessageDialog(this, "House Number cannot be blank!", "Error", JOptionPane.OK_OPTION);
            houseNumberTextField.setBackground(Color.yellow);
        }
        else if(cityTextField.getText().trim().isEmpty())   {
            JOptionPane.showMessageDialog(this, "city cannot be blank!", "Error", JOptionPane.OK_OPTION);
            cityTextField.setBackground(Color.yellow);
        }
        else if (!cityTextField.getText().matches("[a-z A-Z]*")){
            JOptionPane.showMessageDialog(this, "Please enter valid city name!", "Error", JOptionPane.OK_OPTION);
            cityTextField.setBackground(Color.yellow);
        }
        else if(zipCodeTextField.getText().trim().isEmpty())   {
            JOptionPane.showMessageDialog(this, "Zip Code cannot be blank!", "Error", JOptionPane.OK_OPTION);
            zipCodeTextField.setBackground(Color.yellow);
        }
        else if (!zipCodeTextField.getText().matches("\\d{5}")){
            JOptionPane.showMessageDialog(this, "Please enter valid 5 digit Zip Code!", "Error", JOptionPane.OK_OPTION);
            zipCodeTextField.setBackground(Color.yellow);
        }
        else if(occupationTextField.getText().trim().isEmpty())   {
            JOptionPane.showMessageDialog(this, "Please enter Occupation!", "Error", JOptionPane.OK_OPTION);
            occupationTextField.setBackground(Color.yellow);
        }
        else if(emailTextField.getText().trim().isEmpty())   {
            JOptionPane.showMessageDialog(this, "Email ID  cannot be blank!", "Error", JOptionPane.OK_OPTION);
            emailTextField.setBackground(Color.yellow);
        }
        else if(!emailTextField.getText().matches(ePattern))   {
            JOptionPane.showMessageDialog(this, "Please enter valid Email ID!", "Error", JOptionPane.OK_OPTION);
            emailTextField.setBackground(Color.yellow);
        }
        else if(phoneNumberTextField.getText().trim().isEmpty())   {
            JOptionPane.showMessageDialog(this, "Phone Number field cannot be blank!", "Error", JOptionPane.OK_OPTION);
            phoneNumberTextField.setBackground(Color.yellow);
        }
        else if (!phoneNumberTextField.getText().matches("\\d{10}")){
            JOptionPane.showMessageDialog(this, "Please enter valid 10 digit Phone Number!", "Error", JOptionPane.OK_OPTION);
            phoneNumberTextField.setBackground(Color.yellow);
        }
        else if(!dobTextField.getText().matches("((?:19|20)\\d\\d)/(0?[1-9]|1[012])/([12][0-9]|3[01]|0?[1-9])")) {
            JOptionPane.showMessageDialog(this, "Please enter valid Date of Birth in format (YYYY/MM/DD)!", "Error", JOptionPane.OK_OPTION);
            dobTextField.setBackground(Color.yellow);
        }
        else if(communityTextField.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "community field cannot be blank!","Error",JOptionPane.OK_OPTION);
            communityTextField.setBackground(Color.yellow);
        }
        else if (!communityTextField.getText().matches("[a-zA-Z]*")){
            JOptionPane.showMessageDialog(this, "Please enter valid Community name!", "Error", JOptionPane.OK_OPTION);
            communityTextField.setBackground(Color.yellow);
        }
        else    {

            person.setFirstName(firstNameTextField.getText());
            person.setLastName(lastNameTextField.getText());
            person.setMiddleName(middleNameTextField.getText());
            person.setDob(dobTextField.getText());
            person.setHouseNumber(houseNumberTextField.getText());
            person.setCity(cityTextField.getText());
            person.setZipCode(Integer.parseInt(zipCodeTextField.getText()));
            person.setOccupation(occupationTextField.getText());
            person.setEmail(emailTextField.getText());
            person.setPhoneNumber(Long.parseLong(phoneNumberTextField.getText()));
            person.setCommunity(communityTextField.getText());

            personList.add(person);

            JOptionPane.showMessageDialog(this, "Person Information is successfully saved!", "Information", JOptionPane.INFORMATION_MESSAGE);
            resetFields();

            CreatePatientPanel createPatientPanel =  new CreatePatientPanel(person, userProcessContainer);
            userProcessContainer.add("CreatePatientPanel", createPatientPanel);
            CardLayout layout = (CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);

        }
    }//GEN-LAST:event_createBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void houseNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_houseNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_houseNumberTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JTextField communityTextField;
    private javax.swing.JButton createBtn;
    private javax.swing.JTextField dobTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JTextField houseNumberTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JTextField middleNameTextField;
    private javax.swing.JTextField occupationTextField;
    private javax.swing.JTextField phoneNumberTextField;
    private javax.swing.JTextField zipCodeTextField;
    // End of variables declaration//GEN-END:variables

    private void resetFields() {
        firstNameTextField.setText("");
        firstNameTextField.setBackground(Color.white);
        lastNameTextField.setText("");
        lastNameTextField.setBackground(Color.white);
        middleNameTextField.setText("");
        middleNameTextField.setBackground(Color.white);
        dobTextField.setText("");
        dobTextField.setBackground(Color.white);
        houseNumberTextField.setText("");
        houseNumberTextField.setBackground(Color.white);
        cityTextField.setText("");
        cityTextField.setBackground(Color.white);
        zipCodeTextField.setText("");
        zipCodeTextField.setBackground(Color.white);
        occupationTextField.setText("");
        occupationTextField.setBackground(Color.white);
        emailTextField.setText("");
        emailTextField.setBackground(Color.white);
        phoneNumberTextField.setText("");
        phoneNumberTextField.setBackground(Color.white);
        communityTextField.setText("");
        communityTextField.setBackground(Color.white);
    }
}
