/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Person;
import Model.PersonDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author rutuja
 */
public class ProfileWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfileWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private PersonDirectory personDirectory;
    private ArrayList<Person> personList;
    
    public ProfileWorkAreaJPanel(PersonDirectory personDirectory, JPanel userProcessContainer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.personDirectory = personDirectory;
        this.personList = personDirectory.getPersonList();
        this.setSize(3000,3000);
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createProfileBtn = new javax.swing.JButton();
        manageProfileBtn = new javax.swing.JButton();

        createProfileBtn.setBackground(new java.awt.Color(255, 255, 204));
        createProfileBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        createProfileBtn.setText("Create Profile");
        createProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProfileBtnActionPerformed(evt);
            }
        });

        manageProfileBtn.setBackground(new java.awt.Color(255, 255, 204));
        manageProfileBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        manageProfileBtn.setText("Manage Profile");
        manageProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageProfileBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageProfileBtn)
                    .addComponent(createProfileBtn))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(createProfileBtn)
                .addGap(80, 80, 80)
                .addComponent(manageProfileBtn)
                .addContainerGap(82, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProfileBtnActionPerformed
        // TODO add your handling code here:

        CreatePersonPanel createPersonPanel =  new CreatePersonPanel(personDirectory, userProcessContainer);
        userProcessContainer.add("CreatePersonPanel", createPersonPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_createProfileBtnActionPerformed

    private void manageProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageProfileBtnActionPerformed
        // TODO add your handling code here:

        ManageProfilePanel managePanel =  new ManageProfilePanel(personDirectory, userProcessContainer);
        userProcessContainer.add("ManageAccountPanel", managePanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageProfileBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createProfileBtn;
    private javax.swing.JButton manageProfileBtn;
    // End of variables declaration//GEN-END:variables
}
