/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Patient;
import Model.Person;
import Model.VitalSign;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rutuja
 */
public class ViewPatientPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPatientPanel
     */
    private Person person;
    private ArrayList<Patient> patientList;
    private Patient patient;
    private JPanel userProcessContainer;
    private int age;
    
    public ViewPatientPanel(Person person, JPanel userProcessContainer) {
        initComponents();
        this.setSize(3000,3000);
        this.userProcessContainer = userProcessContainer;
        this.person = person;
        patientList = this.person.getPatientList();
        patient = patientList.get(0);
        
        age = patient.getAgeGroup();
        
        ID.setText(String.valueOf(patient.getpID()));
        
        pIDTextField.setText(String.valueOf(patient.getpID()));
        nameTextField.setText(patient.getpName());
        ageTextField.setText(String.valueOf(patient.getAgeGroup()));
        docNameTextField.setText(patient.getDocName());
        pharmacyTextField.setText(patient.getPharmacy());
        
        populateTable();
    }

 
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        patientTable = new javax.swing.JTable();
        addVitalBtn = new javax.swing.JButton();
        ID = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Hint = new javax.swing.JButton();
        pharmacyTextField = new javax.swing.JTextField();
        docNameTextField = new javax.swing.JTextField();
        bp = new javax.swing.JLabel();
        ageTextField = new javax.swing.JTextField();
        heartRate = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        respRate = new javax.swing.JLabel();
        pIDTextField = new javax.swing.JTextField();
        deleteBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        viewBtn = new javax.swing.JButton();
        nameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();

        setBackground(new java.awt.Color(241, 199, 199));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        patientTable.setBackground(new java.awt.Color(204, 255, 255));
        patientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TimeStamp", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(patientTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 164, 638, 212));

        addVitalBtn.setBackground(new java.awt.Color(255, 255, 204));
        addVitalBtn.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        addVitalBtn.setText("Add VitalSign");
        addVitalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVitalBtnActionPerformed(evt);
            }
        });
        add(addVitalBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 388, -1, -1));

        ID.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 16, 96, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 204));
        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel6.setText("Preffered Pharmacy:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 70, -1, -1));

        Hint.setBackground(new java.awt.Color(255, 255, 204));
        Hint.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        Hint.setText("Hint");
        Hint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HintActionPerformed(evt);
            }
        });
        add(Hint, new org.netbeans.lib.awtextra.AbsoluteConstraints(717, 388, -1, -1));

        pharmacyTextField.setEditable(false);
        add(pharmacyTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 68, 130, -1));

        docNameTextField.setEditable(false);
        add(docNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 100, 130, -1));

        bp.setBackground(new java.awt.Color(255, 255, 204));
        bp.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        add(bp, new org.netbeans.lib.awtextra.AbsoluteConstraints(717, 284, 83, 18));

        ageTextField.setEditable(false);
        add(ageTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 132, 130, -1));

        heartRate.setBackground(new java.awt.Color(255, 255, 204));
        heartRate.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        add(heartRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(717, 248, 83, 18));

        jLabel4.setBackground(new java.awt.Color(255, 255, 204));
        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel4.setText("Age:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 134, -1, -1));

        respRate.setBackground(new java.awt.Color(255, 255, 204));
        respRate.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        add(respRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(717, 212, 83, 18));

        pIDTextField.setEditable(false);
        add(pIDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 68, 130, -1));

        deleteBtn.setBackground(new java.awt.Color(255, 255, 204));
        deleteBtn.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        deleteBtn.setText("Delete VitalSign");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 388, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 204));
        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel3.setText("Patient ID:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        viewBtn.setBackground(new java.awt.Color(255, 255, 204));
        viewBtn.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        viewBtn.setText("View VitalSign");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });
        add(viewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 388, -1, -1));

        nameTextField.setEditable(false);
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 100, 130, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 204));
        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel2.setText("Patient Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 102, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Patient Information");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 16, -1, -1));

        backBtn.setBackground(new java.awt.Color(255, 255, 204));
        backBtn.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 21, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 204));
        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel5.setText("Primary Doctor Name:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 102, -1, -1));

        status.setBackground(new java.awt.Color(255, 255, 204));
        status.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(717, 164, 103, 22));
    }// </editor-fold>//GEN-END:initComponents

    private void addVitalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVitalBtnActionPerformed
        // TODO add your handling code here:
        EditVitalSignPanel editVitalSignPanel = new EditVitalSignPanel(patient.getVitalSignHistory(), age, userProcessContainer);
        userProcessContainer.add("EditVitalSignPanel", editVitalSignPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);

       
    }//GEN-LAST:event_addVitalBtnActionPerformed

    private void HintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HintActionPerformed
        // TODO add your handling code here:

        status.setText("Normal Status");

        if((age >= 1) && (age <= 3)) {
            respRate.setText("20-30");
            heartRate.setText("80-130");
            bp.setText("80-110");
        }
        else if((age >= 4) && (age <= 5)) {
            respRate.setText("20-30");
            heartRate.setText("80-120");
            bp.setText("80-110");
        }
        else if((age >= 6) && (age <= 12)) {
            respRate.setText("20-30");
            heartRate.setText("70-110");
            bp.setText("80-120");
        }
        else  {
            respRate.setText("12-20");
            heartRate.setText("55-105");
            bp.setText("110-120");
        }
    }//GEN-LAST:event_HintActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:

        //get the selected row
        int selectedRow = patientTable.getSelectedRow();

        if(selectedRow >= 0)    {

            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this row ?", "Warning!", dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION)  {

                VitalSign vs = (VitalSign)patientTable.getValueAt(selectedRow, 0);
                patient.getVitalSignHistory().deleteVitalSign(vs);

                JOptionPane.showMessageDialog(this, "Patient Information has been deleted", "Information", JOptionPane.INFORMATION_MESSAGE);

                //Populate the new Table after deleting the account
                populateTable();
            }
        }
        else    {
            JOptionPane.showMessageDialog(this, "Please select a row!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:

        int selectedRow = patientTable.getSelectedRow();

        if(selectedRow >= 0)    {
           
            VitalSign vitalSign = (VitalSign)patientTable.getValueAt(selectedRow, 0);
            ViewVitalSignPanel viewVitalSignPanel = new ViewVitalSignPanel(vitalSign, userProcessContainer);
            userProcessContainer.add("ViewVitalSignPanel",viewVitalSignPanel);
            CardLayout layout = (CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        else    {
            JOptionPane.showMessageDialog(this, "Please select a row!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_viewBtnActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    void populateTable() {
        
        DefaultTableModel dtm = (DefaultTableModel)patientTable.getModel();
        
        dtm.setRowCount(0);
        
        for(VitalSign vs :  patient.getVitalSignHistory().getVitalSignList())   {   
            Object row[] = new Object[2];
            
            row[0] = vs;
            
            if(age >= 1 && age <= 3)   {
                if( ((vs.getRespRate() < 20) || (vs.getRespRate() > 30)) ||
                     (vs.getHeartRate() < 80) || (vs.getHeartRate() > 130) ||
                     (vs.getBp() < 80) || (vs.getBp() > 110))
                {
                    row[1] = "Abnormal";
                }
                else    {
                    row[1] = "Normal";
                }
            }
            else if(age >= 4 && age <= 5)   {
                if( ((vs.getRespRate() < 20) || (vs.getRespRate() > 30)) ||
                     (vs.getHeartRate() < 80) || (vs.getHeartRate() > 120) ||
                     (vs.getBp() < 80) || (vs.getBp() >= 110))
                {
                    row[1] = "Abormal";
                }
                else    {
                    row[1] = "Normal";
                }
            }
            else if(age >= 6 && age <= 12)   {
                if( ((vs.getRespRate() < 20) || (vs.getRespRate() > 30)) ||
                     (vs.getHeartRate() < 70) || (vs.getHeartRate() > 110) ||
                     (vs.getBp() < 80) || (vs.getBp() >= 120))
                {
                    row[1] = "Abnormal";
                }
                else    {
                    row[1] = "Normal";
                }
            }
            else {
                if( ((vs.getRespRate() < 12) || (vs.getRespRate() > 20)) ||
                     (vs.getHeartRate() < 55) || (vs.getHeartRate() > 105) ||
                     (vs.getBp() < 110) || (vs.getBp() >= 120))
                {
                    row[1] = "Abnormal";
                }
                else    {
                    row[1] = "Normal";
                }
            }
            
            
            //add each person to the table for dispalay
            dtm.addRow(row);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hint;
    private javax.swing.JLabel ID;
    private javax.swing.JButton addVitalBtn;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel bp;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField docNameTextField;
    private javax.swing.JLabel heartRate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField pIDTextField;
    private javax.swing.JTable patientTable;
    private javax.swing.JTextField pharmacyTextField;
    private javax.swing.JLabel respRate;
    private javax.swing.JLabel status;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
