/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdministrativeRole;

import Business.SupplierDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author rutuja
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdministrativeWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private SupplierDirectory supplierDirectory;
    public AdminWorkAreaJPanel(JPanel userProcessContainer,SupplierDirectory supplierDirectory) {
        
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.supplierDirectory=supplierDirectory;
        this.setSize(2000,2000);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblworkarea = new javax.swing.JLabel();
        lbladminworkrole = new javax.swing.JLabel();
        btnManagerSupplier = new javax.swing.JButton();

        setBackground(new java.awt.Color(144, 177, 177));

        lblworkarea.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblworkarea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblworkarea.setText("WORKAREA");

        lbladminworkrole.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lbladminworkrole.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbladminworkrole.setText("Administrative Work");

        btnManagerSupplier.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        btnManagerSupplier.setText("Manage Suppliers >>");
        btnManagerSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerSupplierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblworkarea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbladminworkrole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(btnManagerSupplier)
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblworkarea)
                .addGap(27, 27, 27)
                .addComponent(lbladminworkrole)
                .addGap(74, 74, 74)
                .addComponent(btnManagerSupplier)
                .addContainerGap(140, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManagerSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerSupplierActionPerformed
        // TODO add your handling code here:
    ManageSuppliers ms = new ManageSuppliers(userProcessContainer , supplierDirectory);
    userProcessContainer.add("ManageSuppliersAdministrative",ms);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManagerSupplierActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManagerSupplier;
    private javax.swing.JLabel lbladminworkrole;
    private javax.swing.JLabel lblworkarea;
    // End of variables declaration//GEN-END:variables
}
