/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userinterface.RestaurantAdminRole;

import Business.DeliveryMan.DeliveryMan;
import Business.DeliveryMan.DeliveryManDirectory;
import Business.Order.Order;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import javax.swing.JPanel;

/**
 *
 * @author rutuja
 */
public class AssignToDeliveryManJPanel extends javax.swing.JPanel {

    /** Creates new form AssignDeliveryManPanel */
    JPanel userProcessContainer;
    Order order;
    UserAccount userAccount;
    Restaurant restaurant;
    DeliveryManDirectory deliveryManDirectory;
    public AssignToDeliveryManJPanel(JPanel userProcessContainer, Order order, DeliveryManDirectory deliveryManDirectory, Restaurant restaurant, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.order = order;
        this.deliveryManDirectory = deliveryManDirectory;
        this.restaurant = restaurant;
        this.userAccount = userAccount;
        dpdDeliveryman.removeAllItems();
        this.populateDeliveryMan();
        orderIdTextField.setEditable(false);
        orderIdTextField.setText(Integer.toString(this.order.getOrderId()));
    }
    private void populateDeliveryMan()
    {
        for(DeliveryMan d: this.deliveryManDirectory.getDeliverymanList())
        {
            dpdDeliveryman.addItem(d.getName());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnAssign = new javax.swing.JButton();
        orderIdTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dpdDeliveryman = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Assign Delivery Man");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 233, 29));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 29, -1, -1));

        jLabel3.setText("Available Delivery person list");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        btnAssign.setText("Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        add(btnAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));
        add(orderIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 190, -1));

        jLabel4.setText("Order id:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        dpdDeliveryman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpdDeliverymanActionPerformed(evt);
            }
        });
        add(dpdDeliveryman, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 199, -1));

        jLabel5.setText("Select DeliveryMan:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your h)andling code here:
        DeliveryMan dm = null;
        String d1 = (String)dpdDeliveryman.getSelectedItem();
        for(DeliveryMan d: this.deliveryManDirectory.getDeliverymanList())
        {
            if(d.getName().equals(d1))
            {
                dm = d;
            }
        }
        for (WorkRequest w : this.restaurant.getWorkQueue().getWorkRequestList()) 
            {
                if((w.getOrder() != null) && (w.getOrder().getOrderId() == order.getOrderId()))
                {
                   w.setSender(this.userAccount);
                   w.setStatus("Assinged to delivery Man");
                   dm.getWorkQueue().getWorkRequestList().add(w);
                   System.out.println("d work " + dm.getWorkQueue().getWorkRequestList());
                   break;
                }
  
            }
    }//GEN-LAST:event_btnAssignActionPerformed

    private void dpdDeliverymanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpdDeliverymanActionPerformed

    }//GEN-LAST:event_dpdDeliverymanActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox dpdDeliveryman;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField orderIdTextField;
    // End of variables declaration//GEN-END:variables

}
