/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.DeliveryMan.DeliveryMan;
import Business.Employee.Employee;
import Business.Restaurant.Menu;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rutuja
 */
public class ManageMenuJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddMenuList
     */
    JPanel userProcessContainer;
    Restaurant restaurant;
    
    
    
    public ManageMenuJPanel(JPanel userProcessContainer, Restaurant restaurant) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.restaurant = restaurant;
        this.populateTable();
        this.btnSave.setVisible(false);
    }
      public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) menuTable.getModel();
        dtm.setRowCount(0);
        for (Menu m : this.restaurant.getMenu()) {
            Object row[] = new Object[2];
                row[0] = m;
                row[1] = m.getPrice();
            dtm.addRow(row);
    }
      
        }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menuTable = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        priceTextField = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        foodItemTextField = new javax.swing.JTextField();
        btnAddMenu = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Menu");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 18, 194, 28));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 20, -1, -1));

        jLabel3.setText("Price ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        jLabel7.setText("Food Item");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        menuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Food Item", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(menuTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 108, 384, 95));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));
        add(priceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 136, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));
        add(foodItemTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 136, -1));

        btnAddMenu.setText("Submit");
        btnAddMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMenuActionPerformed(evt);
            }
        });
        add(btnAddMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        AdminWorkAreaJPanel adminWorkArea = (AdminWorkAreaJPanel) component;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String foodItem = foodItemTextField.getText();
        Float price = Float.parseFloat(priceTextField.getText());
        for(Menu m: this.restaurant.getMenu())
        {
            if(m.getFoodItem().equals(foodItem))
            {
                m.setPrice(price);
            }
        }
        JOptionPane.showMessageDialog(null, "Price updated successfully for food item " + foodItem + " .");        
        this.populateTable();
        this.btnAddMenu.setVisible(true);
        this.foodItemTextField.setEditable(true);
        this.btnSave.setVisible(false);
        foodItemTextField.setText("");
        priceTextField.setText("");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        this.btnAddMenu.setVisible(false);
        this.foodItemTextField.setEditable(false);
        this.btnSave.setVisible(true);
        int selectedRow = menuTable.getSelectedRow();
        if(selectedRow >= 0)
        {
            Menu m = (Menu) menuTable.getValueAt(selectedRow, 0);
            foodItemTextField.setText(m.getFoodItem());
            priceTextField.setText(m.getPrice().toString());
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please select a menu item to delete.");
        }
        this.populateTable();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow = menuTable.getSelectedRow();
        if(selectedRow >= 0)
        {
            Menu m = (Menu) menuTable.getValueAt(selectedRow, 0);
            if(this.restaurant.getMenu().contains(m))
            {
                this.restaurant.getMenu().remove(m);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please select a menu item to delete.");
        }
        this.populateTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    List<Map<String,Float>> iteams = new ArrayList();
    
    private void btnAddMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMenuActionPerformed
String foodItem = foodItemTextField.getText();
        Float price = Float.parseFloat(priceTextField.getText());
        Menu menu = new Menu(foodItem, price);

        this.restaurant.getMenu().add(menu);
        JOptionPane.showMessageDialog(null, "Menu added successfully.");       
        this.populateTable();
        foodItemTextField.setText("");
        priceTextField.setText("");
                                 
    }//GEN-LAST:event_btnAddMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnAddMenu;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTextField foodItemTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable menuTable;
    private javax.swing.JTextField priceTextField;
    // End of variables declaration//GEN-END:variables

      

   
}
