/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.Product;

/**
 *
 * @author rutuja
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    Product product;
    public CreateJPanel(Product product) {
        initComponents();
        this.product = product;
        this.setSize(2000,2000);
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Createlabl = new javax.swing.JLabel();
        namelbl = new javax.swing.JLabel();
        pricelbl = new javax.swing.JLabel();
        quantitylbl = new javax.swing.JLabel();
        descriptionlbl = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        pricetxt = new javax.swing.JTextField();
        quantitytxt = new javax.swing.JTextField();
        descriptiontxt = new javax.swing.JTextField();
        createSavebtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(197, 197, 226));

        Createlabl.setFont(new java.awt.Font("Arial Hebrew", 0, 18)); // NOI18N
        Createlabl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Createlabl.setText("Create Product");

        namelbl.setBackground(new java.awt.Color(197, 197, 226));
        namelbl.setText("Name:");

        pricelbl.setBackground(new java.awt.Color(197, 197, 226));
        pricelbl.setText("Price");

        quantitylbl.setBackground(new java.awt.Color(197, 197, 226));
        quantitylbl.setText("Quantity:");

        descriptionlbl.setBackground(new java.awt.Color(197, 197, 226));
        descriptionlbl.setText("Description:");

        createSavebtn.setText("SAVE");
        createSavebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createSavebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Createlabl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namelbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pricelbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(quantitylbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(descriptionlbl, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descriptiontxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(createSavebtn)))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {descriptiontxt, nametxt, pricetxt, quantitytxt});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Createlabl)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namelbl)
                    .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pricelbl)
                    .addComponent(pricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantitylbl)
                    .addComponent(quantitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descriptionlbl)
                    .addComponent(descriptiontxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(createSavebtn)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {descriptiontxt, nametxt, pricetxt, quantitytxt});

    }// </editor-fold>//GEN-END:initComponents

    private void createSavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createSavebtnActionPerformed
        // TODO add your handling code here:
        product.setName(nametxt.getText());
        product.setPrice(pricetxt.getText());
        product.setAvailnum(quantitytxt.getText());
        product.setDescription(descriptiontxt.getText());
        
        JOptionPane.showMessageDialog(this, "Product information is Saved");
    }//GEN-LAST:event_createSavebtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Createlabl;
    private javax.swing.JButton createSavebtn;
    private javax.swing.JLabel descriptionlbl;
    private javax.swing.JTextField descriptiontxt;
    private javax.swing.JLabel namelbl;
    private javax.swing.JTextField nametxt;
    private javax.swing.JLabel pricelbl;
    private javax.swing.JTextField pricetxt;
    private javax.swing.JLabel quantitylbl;
    private javax.swing.JTextField quantitytxt;
    // End of variables declaration//GEN-END:variables
}
