/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.PersonInfo;

/**
 *
 * @author rutuja
 */
public class CheckingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CheckingJPanel
     */
    PersonInfo personinfo;
    public CheckingJPanel(PersonInfo personinfo) {
        initComponents();
        this.personinfo= personinfo;
        this.setSize(2000,2000);
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkinglbl = new javax.swing.JLabel();
        bnknamelbl = new javax.swing.JLabel();
        routinglbl = new javax.swing.JLabel();
        accballbl = new javax.swing.JLabel();
        actypelbl = new javax.swing.JLabel();
        bnknametxt = new javax.swing.JTextField();
        croutingtxt = new javax.swing.JTextField();
        accbaltxt = new javax.swing.JTextField();
        cacctypetxt = new javax.swing.JTextField();
        accnumlbl = new javax.swing.JLabel();
        accnumtxt = new javax.swing.JTextField();
        chksavebtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 219, 219));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkinglbl.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        checkinglbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        checkinglbl.setText("Checking Account Information");
        add(checkinglbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 450, -1));

        bnknamelbl.setText("Bank Name:");
        add(bnknamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, 20));

        routinglbl.setText("Routing Number:");
        add(routinglbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, 20));

        accballbl.setText("Account Balance:");
        add(accballbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, 20));

        actypelbl.setText("Account Type:");
        add(actypelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, 20));

        bnknametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnknametxtActionPerformed(evt);
            }
        });
        add(bnknametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 80, -1));

        croutingtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                croutingtxtActionPerformed(evt);
            }
        });
        add(croutingtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 80, -1));

        accbaltxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accbaltxtActionPerformed(evt);
            }
        });
        add(accbaltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 80, -1));

        cacctypetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cacctypetxtActionPerformed(evt);
            }
        });
        add(cacctypetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 80, -1));

        accnumlbl.setText("Account Number:");
        add(accnumlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, 20));

        accnumtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accnumtxtActionPerformed(evt);
            }
        });
        add(accnumtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 80, -1));

        chksavebtn.setText("Save");
        chksavebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chksavebtnActionPerformed(evt);
            }
        });
        add(chksavebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void croutingtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_croutingtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_croutingtxtActionPerformed

    private void chksavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chksavebtnActionPerformed
        // TODO add your handling code here:
        personinfo.setcBankName(bnknametxt.getText());
        personinfo.setcRoutingNumber(croutingtxt.getText());
        personinfo.setcBankAccountNumber(accnumtxt.getText());
        personinfo.setcAccountBalance(accbaltxt.getText());
        personinfo.setcAccountType(cacctypetxt.getText());
        
        JOptionPane.showMessageDialog(this, "Checking Bank Account Information Saved.");       
    }//GEN-LAST:event_chksavebtnActionPerformed

    private void bnknametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnknametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnknametxtActionPerformed

    private void accnumtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accnumtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accnumtxtActionPerformed

    private void accbaltxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accbaltxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accbaltxtActionPerformed

    private void cacctypetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cacctypetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cacctypetxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accballbl;
    private javax.swing.JTextField accbaltxt;
    private javax.swing.JLabel accnumlbl;
    private javax.swing.JTextField accnumtxt;
    private javax.swing.JLabel actypelbl;
    private javax.swing.JLabel bnknamelbl;
    private javax.swing.JTextField bnknametxt;
    private javax.swing.JTextField cacctypetxt;
    private javax.swing.JLabel checkinglbl;
    private javax.swing.JButton chksavebtn;
    private javax.swing.JTextField croutingtxt;
    private javax.swing.JLabel routinglbl;
    // End of variables declaration//GEN-END:variables
}
