/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.PersonInfo;

/**
 *
 * @author rutuja
 */
public class LicenceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LicenceJPanel
     */
    PersonInfo personinfo;
    public LicenceJPanel(PersonInfo personinfo) {
        initComponents();
        this.personinfo= personinfo;
        this.setSize(2000,2000);
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        drvlbl = new javax.swing.JLabel();
        drvnumlbl = new javax.swing.JLabel();
        dissuelbl = new javax.swing.JLabel();
        dexpirelbl = new javax.swing.JLabel();
        bloodtypelbl = new javax.swing.JLabel();
        picturelbl = new javax.swing.JLabel();
        drvnumtxt = new javax.swing.JTextField();
        dissuetxt = new javax.swing.JTextField();
        dexpiretxt = new javax.swing.JTextField();
        bloodtypetxt = new javax.swing.JTextField();
        picturetxt = new javax.swing.JTextField();
        dbrowsebtn = new javax.swing.JButton();
        dsavebtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 219, 219));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        drvlbl.setBackground(new java.awt.Color(231, 203, 203));
        drvlbl.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        drvlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        drvlbl.setText("Driver Licence Information");
        add(drvlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 21, 486, -1));

        drvnumlbl.setText("Licence Number:");
        add(drvnumlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 79, -1, -1));

        dissuelbl.setText("Date of Issue:");
        add(dissuelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 111, -1, -1));

        dexpirelbl.setText("Date of expiry:");
        add(dexpirelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 148, -1, -1));

        bloodtypelbl.setText("Blood Type:");
        add(bloodtypelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 186, -1, -1));

        picturelbl.setText("Picture:");
        add(picturelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 224, -1, -1));

        drvnumtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drvnumtxtActionPerformed(evt);
            }
        });
        add(drvnumtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 79, 104, -1));

        dissuetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dissuetxtActionPerformed(evt);
            }
        });
        add(dissuetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 111, 104, -1));

        dexpiretxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dexpiretxtActionPerformed(evt);
            }
        });
        add(dexpiretxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 143, 104, -1));

        bloodtypetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodtypetxtActionPerformed(evt);
            }
        });
        add(bloodtypetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 181, 104, -1));

        picturetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                picturetxtActionPerformed(evt);
            }
        });
        add(picturetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 219, 104, -1));

        dbrowsebtn.setText("Browse");
        dbrowsebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbrowsebtnActionPerformed(evt);
            }
        });
        add(dbrowsebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 275, -1, -1));

        dsavebtn.setText("Save");
        dsavebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dsavebtnActionPerformed(evt);
            }
        });
        add(dsavebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 275, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void drvnumtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drvnumtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drvnumtxtActionPerformed

    private void dissuetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dissuetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dissuetxtActionPerformed

    private void dexpiretxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dexpiretxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dexpiretxtActionPerformed

    private void bloodtypetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodtypetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodtypetxtActionPerformed

    private void picturetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_picturetxtActionPerformed
        // TODO add your handling code here:
                picturetxt.setText("Select an Image using browse option");

    }//GEN-LAST:event_picturetxtActionPerformed

    private void dbrowsebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbrowsebtnActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter flt = new FileNameExtensionFilter(".jpg, .png, .jpeg", "jpg", "png", "jpeg");
        fileChooser.setFileFilter(flt);
        int selected = fileChooser.showOpenDialog(null);
        if(selected == JFileChooser.APPROVE_OPTION) {
            File fle = fileChooser.getSelectedFile();
            String getImagepath = fle.getAbsolutePath();
            JOptionPane.showMessageDialog(null, getImagepath);
            ImageIcon image = new ImageIcon(getImagepath);
            picturetxt.setText(getImagepath);
            personinfo.setPicture(picturetxt.getText());
        
        }
    }//GEN-LAST:event_dbrowsebtnActionPerformed

    private void dsavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dsavebtnActionPerformed
        // TODO add your handling code here:
        personinfo.setlNumber(drvnumtxt.getText());
        personinfo.setDateOfIssue(dissuetxt.getText());
        personinfo.setDateOfExpire(dexpiretxt.getText());
        personinfo.setBloodTyep(bloodtypetxt.getText());
        
        JOptionPane.showMessageDialog(this, "Drivers License Information Saved.");
    }//GEN-LAST:event_dsavebtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bloodtypelbl;
    private javax.swing.JTextField bloodtypetxt;
    private javax.swing.JButton dbrowsebtn;
    private javax.swing.JLabel dexpirelbl;
    private javax.swing.JTextField dexpiretxt;
    private javax.swing.JLabel dissuelbl;
    private javax.swing.JTextField dissuetxt;
    private javax.swing.JLabel drvlbl;
    private javax.swing.JLabel drvnumlbl;
    private javax.swing.JTextField drvnumtxt;
    private javax.swing.JButton dsavebtn;
    private javax.swing.JLabel picturelbl;
    private javax.swing.JTextField picturetxt;
    // End of variables declaration//GEN-END:variables
}
