/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.PersonInfo;

/**
 *
 * @author rutuja
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    PersonInfo personinfo;
    public MainJFrame() {
        initComponents();
        personinfo = new PersonInfo();
        this.setSize(2000, 2000);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        workareaPanel = new javax.swing.JPanel();
        controlPanel = new javax.swing.JPanel();
        menulbl = new javax.swing.JLabel();
        demolbl = new javax.swing.JLabel();
        demobtn = new javax.swing.JButton();
        demoviewbtn = new javax.swing.JButton();
        addrlbl = new javax.swing.JLabel();
        addrbtn = new javax.swing.JButton();
        addrviewbtn = new javax.swing.JButton();
        Savinglbl = new javax.swing.JLabel();
        savingbtn = new javax.swing.JButton();
        savingviewbtn = new javax.swing.JButton();
        checkinglbl = new javax.swing.JLabel();
        checkingbtn = new javax.swing.JButton();
        checkviewbtn = new javax.swing.JButton();
        dlicencelbl = new javax.swing.JLabel();
        driverbtn = new javax.swing.JButton();
        driverviewbtn = new javax.swing.JButton();
        medicallbl = new javax.swing.JLabel();
        medicalbtn = new javax.swing.JButton();
        medicalviewbtn = new javax.swing.JButton();
        Reportlbl = new javax.swing.JLabel();
        reportbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        workareaPanel.setBackground(new java.awt.Color(229, 196, 196));

        javax.swing.GroupLayout workareaPanelLayout = new javax.swing.GroupLayout(workareaPanel);
        workareaPanel.setLayout(workareaPanelLayout);
        workareaPanelLayout.setHorizontalGroup(
            workareaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );
        workareaPanelLayout.setVerticalGroup(
            workareaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(workareaPanel);

        controlPanel.setBackground(new java.awt.Color(229, 196, 196));
        controlPanel.setPreferredSize(new java.awt.Dimension(200, 500));

        menulbl.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        menulbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menulbl.setText("MENU");

        demolbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        demolbl.setText("Demographic Information");

        demobtn.setText("Create");
        demobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demobtnActionPerformed(evt);
            }
        });

        demoviewbtn.setText("View");
        demoviewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demoviewbtnActionPerformed(evt);
            }
        });

        addrlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addrlbl.setText("Address Information");

        addrbtn.setText("Create");
        addrbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrbtnActionPerformed(evt);
            }
        });

        addrviewbtn.setText("View");

        Savinglbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Savinglbl.setText("Saving Account Information");

        savingbtn.setText("Create");

        savingviewbtn.setText("View");

        checkinglbl.setText("Checking Account Information");

        checkingbtn.setText("Create");

        checkviewbtn.setText("View");

        dlicencelbl.setText("Driver's Licence Information");

        driverbtn.setText("Create");
        driverbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driverbtnActionPerformed(evt);
            }
        });

        driverviewbtn.setText("View");

        medicallbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        medicallbl.setText("Medical Record Information");

        medicalbtn.setText("Create");
        medicalbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicalbtnActionPerformed(evt);
            }
        });

        medicalviewbtn.setText("View");

        Reportlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Reportlbl.setText("Report");

        reportbtn.setText("Report ");
        reportbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addComponent(demobtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(demoviewbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addComponent(addrbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addrviewbtn))
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addComponent(savingbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(savingviewbtn))
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addComponent(checkingbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkviewbtn))
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addComponent(driverbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(driverviewbtn))
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addComponent(medicalbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(medicalviewbtn))
                    .addComponent(reportbtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(demolbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addrlbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Savinglbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkinglbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dlicencelbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medicallbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reportlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addComponent(menulbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        controlPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addrbtn, addrviewbtn, checkingbtn, checkviewbtn, demobtn, demoviewbtn, driverbtn, driverviewbtn, medicalbtn, medicalviewbtn, reportbtn, savingbtn, savingviewbtn});

        controlPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Savinglbl, addrlbl, checkinglbl, demolbl, dlicencelbl, medicallbl});

        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(menulbl)
                .addGap(18, 18, 18)
                .addComponent(demolbl)
                .addGap(18, 18, 18)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(demobtn)
                    .addComponent(demoviewbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addrlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addrbtn)
                    .addComponent(addrviewbtn))
                .addGap(18, 18, 18)
                .addComponent(Savinglbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savingbtn)
                    .addComponent(savingviewbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkinglbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkingbtn)
                    .addComponent(checkviewbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dlicencelbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(driverbtn)
                    .addComponent(driverviewbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(medicallbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medicalbtn)
                    .addComponent(medicalviewbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Reportlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reportbtn)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        controlPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addrbtn, addrviewbtn, checkingbtn, checkviewbtn, demobtn, demoviewbtn, driverbtn, driverviewbtn, medicalbtn, medicalviewbtn, reportbtn, savingbtn, savingviewbtn});

        controlPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Savinglbl, addrlbl, checkinglbl, demolbl, dlicencelbl, medicallbl});

        splitPane.setLeftComponent(controlPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void demobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demobtnActionPerformed
        // TODO add your handling code here:
        DemoJPanel demo = new DemoJPanel(personinfo);
        splitPane.setRightComponent(demo);
    }//GEN-LAST:event_demobtnActionPerformed

    private void demoviewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demoviewbtnActionPerformed
        // TODO add your handling code here:
        ViewDemoJPanel viewdemo = new ViewDemoJPanel(personinfo);
        splitPane.setRightComponent(viewdemo);
        
    }//GEN-LAST:event_demoviewbtnActionPerformed

    private void addrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrbtnActionPerformed
        // TODO add your handling code here:
        AddressJPanel address = new AddressJPanel(personinfo);
        splitPane.setRightComponent(address);
    }//GEN-LAST:event_addrbtnActionPerformed
    
    private void driverbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driverbtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_driverbtnActionPerformed

    private void medicalbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicalbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicalbtnActionPerformed

    private void reportbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reportbtnActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Reportlbl;
    private javax.swing.JLabel Savinglbl;
    private javax.swing.JButton addrbtn;
    private javax.swing.JLabel addrlbl;
    private javax.swing.JButton addrviewbtn;
    private javax.swing.JButton checkingbtn;
    private javax.swing.JLabel checkinglbl;
    private javax.swing.JButton checkviewbtn;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JButton demobtn;
    private javax.swing.JLabel demolbl;
    private javax.swing.JButton demoviewbtn;
    private javax.swing.JLabel dlicencelbl;
    private javax.swing.JButton driverbtn;
    private javax.swing.JButton driverviewbtn;
    private javax.swing.JButton medicalbtn;
    private javax.swing.JLabel medicallbl;
    private javax.swing.JButton medicalviewbtn;
    private javax.swing.JLabel menulbl;
    private javax.swing.JButton reportbtn;
    private javax.swing.JButton savingbtn;
    private javax.swing.JButton savingviewbtn;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workareaPanel;
    // End of variables declaration//GEN-END:variables
}
