/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.ImageIcon;
import model.PersonInfo;

/**
 *
 * @author rutuja
 */
public class ReportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportJPanel
     */
    PersonInfo personinfo;
    public ReportJPanel(PersonInfo Personinfo) {
        initComponents();
        this.personinfo= personinfo;
        this.setSize(2000,2000);
        displaypersoninfo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Addrlbl = new javax.swing.JLabel();
        Strlbl = new javax.swing.JLabel();
        Citylbl = new javax.swing.JLabel();
        Statelbl = new javax.swing.JLabel();
        ziplbl = new javax.swing.JLabel();
        streettxt = new javax.swing.JTextField();
        citytxt = new javax.swing.JTextField();
        statetxt = new javax.swing.JTextField();
        ziptxt = new javax.swing.JTextField();
        demolbl = new javax.swing.JLabel();
        fnamelbl = new javax.swing.JLabel();
        lnamelbl = new javax.swing.JLabel();
        doblbl = new javax.swing.JLabel();
        agelbl = new javax.swing.JLabel();
        hgtlbl = new javax.swing.JLabel();
        Phonenumlbl = new javax.swing.JLabel();
        ssnlbl = new javax.swing.JLabel();
        fnametxt = new javax.swing.JTextField();
        lnametxt = new javax.swing.JTextField();
        dobtxt = new javax.swing.JTextField();
        agetxt = new javax.swing.JTextField();
        hgttxt = new javax.swing.JTextField();
        phonenumtxt = new javax.swing.JTextField();
        ssntxt = new javax.swing.JTextField();
        wgttxt1 = new javax.swing.JTextField();
        wgtlbl1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        drvnumtxt = new javax.swing.JTextField();
        dissuetxt = new javax.swing.JTextField();
        dexpiretxt = new javax.swing.JTextField();
        bloodtypetxt = new javax.swing.JTextField();
        picturetxt = new javax.swing.JTextField();
        drvlbl = new javax.swing.JLabel();
        drvnumlbl = new javax.swing.JLabel();
        dissuelbl = new javax.swing.JLabel();
        dexpirelbl = new javax.swing.JLabel();
        bloodtypelbl = new javax.swing.JLabel();
        picturelbl = new javax.swing.JLabel();
        mednumlbl = new javax.swing.JLabel();
        allr1lbl = new javax.swing.JLabel();
        allr2lbl = new javax.swing.JLabel();
        mednumtxt = new javax.swing.JTextField();
        allr1txt = new javax.swing.JTextField();
        allr2txt = new javax.swing.JTextField();
        allr3lbl = new javax.swing.JLabel();
        allr3txt = new javax.swing.JTextField();
        medicallbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        savacclbl = new javax.swing.JLabel();
        accblbl = new javax.swing.JLabel();
        acctypelbl = new javax.swing.JLabel();
        banktxt = new javax.swing.JTextField();
        routingtxt = new javax.swing.JTextField();
        savacctxt = new javax.swing.JTextField();
        accbtxt = new javax.swing.JTextField();
        savinglbl = new javax.swing.JLabel();
        acctypetxt = new javax.swing.JTextField();
        banklbl = new javax.swing.JLabel();
        routinglbl = new javax.swing.JLabel();
        checkinglbl = new javax.swing.JLabel();
        chkaccnumlbl = new javax.swing.JLabel();
        chkaccblbl = new javax.swing.JLabel();
        chkacctyelbl = new javax.swing.JLabel();
        chkbnktxt = new javax.swing.JTextField();
        chkroutingtxt = new javax.swing.JTextField();
        chkaccnumtxt = new javax.swing.JTextField();
        chkaccbaltxt = new javax.swing.JTextField();
        chkacctypetxt = new javax.swing.JTextField();
        chkbnklbl = new javax.swing.JLabel();
        chkroutlbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(248, 169, 169));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REPORT");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 15, 1060, 25));

        jPanel1.setBackground(new java.awt.Color(230, 197, 197));

        Addrlbl.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        Addrlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Addrlbl.setText("Addresss Information");

        Strlbl.setText("Street Address:");

        Citylbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Citylbl.setText("City:");

        Statelbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Statelbl.setText("State:");

        ziplbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ziplbl.setText("Zip:");

        streettxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streettxtActionPerformed(evt);
            }
        });

        citytxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citytxtActionPerformed(evt);
            }
        });

        demolbl.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        demolbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        demolbl.setText("Demographic Information");

        fnamelbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fnamelbl.setText("First Name:");
        fnamelbl.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                fnamelblComponentHidden(evt);
            }
        });

        lnamelbl.setText("Lastname:");

        doblbl.setText("Date Of Birth:");

        agelbl.setText("Age:");

        hgtlbl.setText("Height:");

        Phonenumlbl.setText("Phone Number:");

        ssnlbl.setText("SSN:");

        fnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnametxtActionPerformed(evt);
            }
        });

        agetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agetxtActionPerformed(evt);
            }
        });

        hgttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hgttxtActionPerformed(evt);
            }
        });

        wgtlbl1.setText("Weight:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Addrlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Strlbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Citylbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Statelbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ziplbl, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(citytxt, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(streettxt)
                            .addComponent(statetxt)
                            .addComponent(ziptxt)))
                    .addComponent(demolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(ssnlbl))
                            .addComponent(Phonenumlbl)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(wgtlbl1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(hgtlbl))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(agelbl))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(doblbl))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(lnamelbl))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(fnamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fnametxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lnametxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dobtxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(agetxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hgttxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(wgttxt1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(phonenumtxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ssntxt, javax.swing.GroupLayout.Alignment.TRAILING)))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {citytxt, statetxt, streettxt, ziptxt});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {agetxt, dobtxt, fnametxt, hgttxt, lnametxt, phonenumtxt, ssntxt, wgttxt1});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(demolbl)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lnamelbl)
                    .addComponent(lnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(doblbl))
                    .addComponent(dobtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agelbl)
                    .addComponent(agetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hgtlbl)
                    .addComponent(hgttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wgtlbl1)
                    .addComponent(wgttxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Phonenumlbl))
                    .addComponent(phonenumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(ssnlbl))
                    .addComponent(ssntxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(Addrlbl)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Strlbl)
                    .addComponent(streettxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Citylbl)
                    .addComponent(citytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Statelbl)
                    .addComponent(statetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ziplbl)
                    .addComponent(ziptxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {agetxt, dobtxt, fnametxt, hgttxt, lnametxt, phonenumtxt, ssntxt, wgttxt1});

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 70, -1, 651));

        jPanel2.setBackground(new java.awt.Color(235, 206, 206));

        drvnumtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drvnumtxtActionPerformed(evt);
            }
        });

        dissuetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dissuetxtActionPerformed(evt);
            }
        });

        dexpiretxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dexpiretxtActionPerformed(evt);
            }
        });

        bloodtypetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodtypetxtActionPerformed(evt);
            }
        });

        picturetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                picturetxtActionPerformed(evt);
            }
        });

        drvlbl.setBackground(new java.awt.Color(231, 203, 203));
        drvlbl.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        drvlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        drvlbl.setText("Driver Licence Information");

        drvnumlbl.setText("Licence Number:");

        dissuelbl.setText("Date of Issue:");

        dexpirelbl.setText("Date of expiry:");

        bloodtypelbl.setText("Blood Type:");

        picturelbl.setText("Picture:");

        mednumlbl.setText("Medical Record Number ");

        allr1lbl.setText("Allergy 1");

        allr2lbl.setText("Allergy 2");

        allr1txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allr1txtActionPerformed(evt);
            }
        });

        allr3lbl.setText("Allergy 3");

        medicallbl.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        medicallbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        medicallbl.setText("Medical Record Information");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(drvnumlbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dissuelbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dexpirelbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bloodtypelbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(picturelbl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bloodtypetxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(drvnumtxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dissuetxt)
                    .addComponent(dexpiretxt)
                    .addComponent(picturetxt, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(allr3lbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mednumlbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(allr1lbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(allr2lbl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(allr1txt, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(mednumtxt)
                    .addComponent(allr2txt)
                    .addComponent(allr3txt, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(medicallbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(drvlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {allr1txt, allr2txt, allr3txt, mednumtxt});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(drvlbl)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(drvnumlbl)
                    .addComponent(drvnumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dissuelbl)
                    .addComponent(dissuetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dexpirelbl)
                    .addComponent(dexpiretxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bloodtypelbl)
                    .addComponent(bloodtypetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(picturelbl)
                    .addComponent(picturetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(medicallbl)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mednumlbl)
                    .addComponent(mednumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allr1lbl)
                    .addComponent(allr1txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allr2lbl)
                    .addComponent(allr2txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allr3lbl)
                    .addComponent(allr3txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 70, -1, 651));

        jPanel3.setBackground(new java.awt.Color(235, 204, 204));

        savacclbl.setText("Saving Account Number:");

        accblbl.setText("Account Balance:");

        acctypelbl.setText("Account Type:");

        routingtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routingtxtActionPerformed(evt);
            }
        });

        savinglbl.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        savinglbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        savinglbl.setText("Saving Account Information");

        banklbl.setText("Bank Name:");

        routinglbl.setText("Routing Number:");

        checkinglbl.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        checkinglbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        checkinglbl.setText("Checking Account Information");

        chkaccnumlbl.setText("Checking Account Number:");

        chkaccblbl.setText("Account Balance:");

        chkacctyelbl.setText("Account Type:");

        chkroutingtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkroutingtxtActionPerformed(evt);
            }
        });

        chkbnklbl.setText("Bank Name:");

        chkroutlbl.setText("Routing Number:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(banklbl)
                    .addComponent(routinglbl)
                    .addComponent(savacclbl)
                    .addComponent(accblbl)
                    .addComponent(acctypelbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(accbtxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(savacctxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(routingtxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(banktxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(acctypetxt, javax.swing.GroupLayout.Alignment.LEADING)))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(savinglbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chkbnklbl)
                            .addComponent(chkroutlbl)
                            .addComponent(chkaccnumlbl)
                            .addComponent(chkaccblbl)
                            .addComponent(chkacctyelbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(chkaccbaltxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkaccnumtxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkroutingtxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkbnktxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkacctypetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(checkinglbl, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(savinglbl)
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(banklbl)
                    .addComponent(banktxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(routinglbl)
                    .addComponent(routingtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savacclbl)
                    .addComponent(savacctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accbtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accblbl))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acctypelbl)
                    .addComponent(acctypetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(checkinglbl)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkbnklbl)
                    .addComponent(chkbnktxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkroutlbl)
                    .addComponent(chkroutingtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkaccnumlbl)
                    .addComponent(chkaccnumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkaccbaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkaccblbl))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkacctyelbl)
                    .addComponent(chkacctypetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(706, 70, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void streettxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streettxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streettxtActionPerformed

    private void citytxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citytxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_citytxtActionPerformed

    private void picturetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_picturetxtActionPerformed
        // TODO add your handling code here:
        picturetxt.setText("Select an Image using browse option");
    }//GEN-LAST:event_picturetxtActionPerformed

    private void bloodtypetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodtypetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodtypetxtActionPerformed

    private void dexpiretxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dexpiretxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dexpiretxtActionPerformed

    private void dissuetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dissuetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dissuetxtActionPerformed

    private void drvnumtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drvnumtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drvnumtxtActionPerformed

    private void allr1txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allr1txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allr1txtActionPerformed

    private void routingtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routingtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_routingtxtActionPerformed

    private void chkroutingtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkroutingtxtActionPerformed
        // TODO add your handling code here:
        chkacctypetxt.setText("Savings");
    }//GEN-LAST:event_chkroutingtxtActionPerformed

    private void fnamelblComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_fnamelblComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_fnamelblComponentHidden

    private void fnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnametxtActionPerformed

    private void agetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agetxtActionPerformed

    private void hgttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hgttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hgttxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Addrlbl;
    private javax.swing.JLabel Citylbl;
    private javax.swing.JLabel Phonenumlbl;
    private javax.swing.JLabel Statelbl;
    private javax.swing.JLabel Strlbl;
    private javax.swing.JLabel accblbl;
    private javax.swing.JTextField accbtxt;
    private javax.swing.JLabel acctypelbl;
    private javax.swing.JTextField acctypetxt;
    private javax.swing.JLabel agelbl;
    private javax.swing.JTextField agetxt;
    private javax.swing.JLabel allr1lbl;
    private javax.swing.JTextField allr1txt;
    private javax.swing.JLabel allr2lbl;
    private javax.swing.JTextField allr2txt;
    private javax.swing.JLabel allr3lbl;
    private javax.swing.JTextField allr3txt;
    private javax.swing.JLabel banklbl;
    private javax.swing.JTextField banktxt;
    private javax.swing.JLabel bloodtypelbl;
    private javax.swing.JTextField bloodtypetxt;
    private javax.swing.JLabel checkinglbl;
    private javax.swing.JTextField chkaccbaltxt;
    private javax.swing.JLabel chkaccblbl;
    private javax.swing.JLabel chkaccnumlbl;
    private javax.swing.JTextField chkaccnumtxt;
    private javax.swing.JLabel chkacctyelbl;
    private javax.swing.JTextField chkacctypetxt;
    private javax.swing.JLabel chkbnklbl;
    private javax.swing.JTextField chkbnktxt;
    private javax.swing.JTextField chkroutingtxt;
    private javax.swing.JLabel chkroutlbl;
    private javax.swing.JTextField citytxt;
    private javax.swing.JLabel demolbl;
    private javax.swing.JLabel dexpirelbl;
    private javax.swing.JTextField dexpiretxt;
    private javax.swing.JLabel dissuelbl;
    private javax.swing.JTextField dissuetxt;
    private javax.swing.JLabel doblbl;
    private javax.swing.JTextField dobtxt;
    private javax.swing.JLabel drvlbl;
    private javax.swing.JLabel drvnumlbl;
    private javax.swing.JTextField drvnumtxt;
    private javax.swing.JLabel fnamelbl;
    private javax.swing.JTextField fnametxt;
    private javax.swing.JLabel hgtlbl;
    private javax.swing.JTextField hgttxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lnamelbl;
    private javax.swing.JTextField lnametxt;
    private javax.swing.JLabel medicallbl;
    private javax.swing.JLabel mednumlbl;
    private javax.swing.JTextField mednumtxt;
    private javax.swing.JTextField phonenumtxt;
    private javax.swing.JLabel picturelbl;
    private javax.swing.JTextField picturetxt;
    private javax.swing.JLabel routinglbl;
    private javax.swing.JTextField routingtxt;
    private javax.swing.JLabel savacclbl;
    private javax.swing.JTextField savacctxt;
    private javax.swing.JLabel savinglbl;
    private javax.swing.JLabel ssnlbl;
    private javax.swing.JTextField ssntxt;
    private javax.swing.JTextField statetxt;
    private javax.swing.JTextField streettxt;
    private javax.swing.JLabel wgtlbl1;
    private javax.swing.JTextField wgttxt1;
    private javax.swing.JLabel ziplbl;
    private javax.swing.JTextField ziptxt;
    // End of variables declaration//GEN-END:variables

    private void displaypersoninfo() {
        fnametxt.setText(personinfo.getFirstName());
        lnametxt.setText(personinfo.getLastName());
        dobtxt.setText(personinfo.getDOB());
        phonenumtxt.setText(personinfo.getPhoneNumber());
        agetxt.setText(personinfo.getAge());
        hgttxt.setText(personinfo.getHeight());
        wgttxt1.setText(personinfo.getWeight());
        ssntxt.setText(personinfo.getSSN());
        
        streettxt.setText(personinfo.getStreetAddress());
        citytxt.setText(personinfo.getCity());
        statetxt.setText(personinfo.getState());
        ziptxt.setText(personinfo.getZipCode());
        
        banktxt.setText(personinfo.getsBankName());
        routingtxt.setText(personinfo.getsRoutingNumber());
        savacctxt.setText(personinfo.getsBnkAccountNumber());
        accbtxt.setText(personinfo.getsAccountBalance());
        acctypetxt.setText(personinfo.getsAccountType());
        
        chkbnktxt.setText(personinfo.getcBankName());
        chkroutingtxt.setText(personinfo.getcRoutingNumber());
        chkaccnumtxt.setText(personinfo.getcBankAccountNumber());
        chkaccbaltxt.setText(personinfo.getcAccountBalance());
        chkacctypetxt.setText(personinfo.getcAccountType());
        
        drvnumtxt.setText(personinfo.getlNumber());
        dissuetxt.setText(personinfo.getDateOfIssue());
        dexpiretxt.setText(personinfo.getDateOfExpire());
        bloodtypetxt.setText(personinfo.getBloodTyep());
        picturetxt.setText(personinfo.getPicture());
        
        mednumtxt.setText(personinfo.getMedicalRecordNum());
        allr1txt.setText(personinfo.getAlergy1());
        allr2txt.setText(personinfo.getAlergy2());
        allr3txt.setText(personinfo.getAlergy3());
        
        String getImagepath = picturetxt.getText();
        ImageIcon myimage = new ImageIcon(getImagepath);
        picturelbl.setIcon(myimage); 
        
        
        
        
    }
}
