/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.PersonInfo;

/**
 *
 * @author rutuja
 */
public class ViewDemoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewDemoJPanel
     */
    PersonInfo personinfo;
    public ViewDemoJPanel(PersonInfo personinfo) {
        initComponents();
        initComponents();
        this.setSize(2000, 2000);
        this.personinfo = personinfo;
        displayperson();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        demolbl = new javax.swing.JLabel();
        fnamelbl = new javax.swing.JLabel();
        lnamelbl = new javax.swing.JLabel();
        doblbl = new javax.swing.JLabel();
        agelbl = new javax.swing.JLabel();
        hgtlbl = new javax.swing.JLabel();
        wgtlbl = new javax.swing.JLabel();
        ssnlbl = new javax.swing.JLabel();
        fnametxt = new javax.swing.JTextField();
        lnametxt = new javax.swing.JTextField();
        dobtxt = new javax.swing.JTextField();
        agetxt = new javax.swing.JTextField();
        hgttxt = new javax.swing.JTextField();
        wgttxt = new javax.swing.JTextField();
        ssntxt = new javax.swing.JTextField();
        Phonenumlbl = new javax.swing.JLabel();
        phonenumtxt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 216, 211));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        demolbl.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        demolbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        demolbl.setText("Demographic Information");
        add(demolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 45, 500, -1));

        fnamelbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fnamelbl.setText("First Name:");
        fnamelbl.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                fnamelblComponentHidden(evt);
            }
        });
        add(fnamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 103, 85, -1));

        lnamelbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lnamelbl.setText("Lastname:");
        add(lnamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 135, 85, -1));

        doblbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        doblbl.setText("Date Of Birth:");
        add(doblbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 165, -1, -1));

        agelbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        agelbl.setText("Age:");
        add(agelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 197, 85, -1));

        hgtlbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        hgtlbl.setText("Height:");
        add(hgtlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 233, 85, -1));

        wgtlbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        wgtlbl.setText("Weight:");
        add(wgtlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 269, 85, -1));

        ssnlbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ssnlbl.setText("SSN:");
        add(ssnlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 343, 85, -1));

        fnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnametxtActionPerformed(evt);
            }
        });
        add(fnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 98, 104, -1));
        add(lnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 135, 104, -1));
        add(dobtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 161, 104, -1));

        agetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agetxtActionPerformed(evt);
            }
        });
        add(agetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 197, 104, -1));

        hgttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hgttxtActionPerformed(evt);
            }
        });
        add(hgttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 233, 104, -1));
        add(wgttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 269, 104, -1));
        add(ssntxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 338, 104, -1));

        Phonenumlbl.setText("Phone Number:");
        add(Phonenumlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 314, -1, -1));
        add(phonenumtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 309, 104, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void fnamelblComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_fnamelblComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_fnamelblComponentHidden

    private void fnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnametxtActionPerformed

    private void agetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agetxtActionPerformed

    private void hgttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hgttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hgttxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Phonenumlbl;
    private javax.swing.JLabel agelbl;
    private javax.swing.JTextField agetxt;
    private javax.swing.JLabel demolbl;
    private javax.swing.JLabel doblbl;
    private javax.swing.JTextField dobtxt;
    private javax.swing.JLabel fnamelbl;
    private javax.swing.JTextField fnametxt;
    private javax.swing.JLabel hgtlbl;
    private javax.swing.JTextField hgttxt;
    private javax.swing.JLabel lnamelbl;
    private javax.swing.JTextField lnametxt;
    private javax.swing.JTextField phonenumtxt;
    private javax.swing.JLabel ssnlbl;
    private javax.swing.JTextField ssntxt;
    private javax.swing.JLabel wgtlbl;
    private javax.swing.JTextField wgttxt;
    // End of variables declaration//GEN-END:variables

    private void displayperson() {
        fnametxt.setText(personinfo.getFirstName());
        lnametxt.setText(personinfo.getLastName());
        dobtxt.setText(personinfo.getDOB());
        agetxt.setText(personinfo.getAge());
        hgttxt.setText(personinfo.getHeight());
        wgttxt.setText(personinfo.getWeight());
        ssntxt.setText(personinfo.getSSN());
        phonenumtxt.setText(personinfo.getPhoneNumber());
        
        
    }
}
