/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.PersonInfo;

/**
 *
 * @author rutuja
 */
public class ViewSavingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewSavingJPanel
     */
    PersonInfo personinfo;
    public ViewSavingJPanel(PersonInfo personinfo) {
        initComponents();
        this.personinfo= personinfo;
        this.setSize(2000,2000);
        displayperson();
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        savinglbl = new javax.swing.JLabel();
        banklbl = new javax.swing.JLabel();
        routinglbl = new javax.swing.JLabel();
        savacclbl = new javax.swing.JLabel();
        accblbl = new javax.swing.JLabel();
        acctypelbl = new javax.swing.JLabel();
        banktxt = new javax.swing.JTextField();
        routingtxt = new javax.swing.JTextField();
        savacctxt = new javax.swing.JTextField();
        accbtxt = new javax.swing.JTextField();
        acctypetxt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 219, 219));

        savinglbl.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        savinglbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        savinglbl.setText("Saving Account Information");

        banklbl.setText("Bank Name:");

        routinglbl.setText("Routing Number:");

        savacclbl.setText("Saving Account Number:");

        accblbl.setText("Account Balance:");

        acctypelbl.setText("Account Type:");

        routingtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routingtxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(savinglbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(65, 65, 65)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(banklbl)
                                .addComponent(routinglbl)
                                .addComponent(savacclbl)
                                .addComponent(accblbl)
                                .addComponent(acctypelbl))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(accbtxt)
                                .addComponent(savacctxt)
                                .addComponent(routingtxt)
                                .addComponent(banktxt)
                                .addComponent(acctypetxt, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(savinglbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(29, 29, 29)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(banklbl)
                        .addComponent(banktxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(routinglbl)
                        .addComponent(routingtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(19, 19, 19)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(savacclbl)
                        .addComponent(savacctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(25, 25, 25)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(accbtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(accblbl))
                    .addGap(17, 17, 17)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(acctypelbl)
                        .addComponent(acctypetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(60, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void routingtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routingtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_routingtxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accblbl;
    private javax.swing.JTextField accbtxt;
    private javax.swing.JLabel acctypelbl;
    private javax.swing.JTextField acctypetxt;
    private javax.swing.JLabel banklbl;
    private javax.swing.JTextField banktxt;
    private javax.swing.JLabel routinglbl;
    private javax.swing.JTextField routingtxt;
    private javax.swing.JLabel savacclbl;
    private javax.swing.JTextField savacctxt;
    private javax.swing.JLabel savinglbl;
    // End of variables declaration//GEN-END:variables

    private void displayperson() {
        banktxt.setText(personinfo.getsBankName());
        routingtxt.setText(personinfo.getsRoutingNumber());
        savacctxt.setText(personinfo.getsBnkAccountNumber());
        accbtxt.setText(personinfo.getsAccountBalance());
        acctypetxt.setText(personinfo.getsAccountType());       
    }
}
